name: bloc_setup
description: "A new Flutter project."
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttrfly: 
    path: packages/fluttrfly
  cupertino_icons: ^1.0.8
  go_router: ^14.2.6
  get_it: ^7.7.0
  injectable: ^2.4.4
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  dartz: ^0.10.1
  intl: ^0.19.0
  firebase_crashlytics: ^4.1.3
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  animated_custom_dropdown: ^3.1.1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.8  
  injectable_generator: ^2.6.1

flutter:
  assets: 
    - assets/
    - assets/images/
    - assets/logo/
  uses-material-design: true

flutter_launcher_icons: 
  android: 'ic_launcher'
  image_path: 'assets/logo/logo.png'
  ios: false
  min_sdk_android: 21
  macos: 
    generate: true
    image_path: 'assets/logo/logo.png'
