name: fluttrfly
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.2.9
  google_fonts: ^6.2.1
  http: ^1.2.1
  file_picker: ^8.1.2
  image_picker: ^1.0.0
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  injectable_generator: ^2.6.1


flutter:
  assets: 
    - assets/
    - assets/svg/
    - assets/png/
  uses-material-design: true
